version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Login ECR Repository...
      - $(aws ecr get-login --region $AWS_REGION_NAME --no-include-email)
  #
  build:
    commands:
      - echo Building the docker image...
      - >
        docker build
        --build-arg ##Environment Variable
        -t
        $SERVICE_NAME/latest
        .
      - >
        docker tag
        $SERVICE_NAME/latest
        ## ECR Repository Arn
  post_build:
    commands:
      - echo Pushing the docker image to ecr...
      - >
        docker push
        ## ECR Repository Arn
      - echo Create taskdefinition template and register it...
      - sh UpdateTaskdefinition.sh
      - printf '[{"name":"xxx","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:xxx > taskdefinition.json
      - cat taskdefinition.json

artifacts:
  files:
      - taskdefinition.json

