AWSTemplateFormatVersion: '2010-09-09'
Description: Create assume policy. This Policy is possible to use other account role.
             Use it together with assume role from other accounts.

Resources:
  AssumePolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyName: root
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Resource: '*'
      Roles:
        - xxx
